version: '3'

services:
  gql-cli:
    container_name: graphql-talk
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:cached
    command: tail -f /dev/null
    ports:
      - "8181:80"


